### PR TITLE
Specify how we encode null messages

### LINKED ISSUE #4: Clarify null values for messages

### PR DESCRIPTION
**Pull request by arj03**
To fix #4

### CODE REVIEW

**Comment by cryptix** [comment]
I believe this information deserves a place on the bendy-butt spec, too.

**Comment by arj03** [comment]
Yeah good idea, so this means you are okay with this solution? :)

**Comment by cryptix** [comment]
yes! SGTM

**Comment by arj03** [comment]
This turned out to be a bigger change in the [JS](https://github.com/ssb-ngi-pointer/ssb-bfe/commit/2f3a315cba3081eea9d48ef63303d6cc2ff1b8db) implementation than I expected. cc @mycognosist

**Comment by arj03** [comment]
Also it seems the [test vector](https://github.com/ssb-ngi-pointer/go-metafeed/blob/master/testvector-metafeed-managment.json) encodes the null values in the tangle as value type null (0x0602) instead of a bendy butt null msg value :)

**Comment by cryptix** [comment]
> null values in the tangle as value type null

Good catch. This was assuming we use [case 3](https://github.com/ssb-ngi-pointer/ssb-binary-field-encodings-spec/issues/4#issuecomment-877182575) on content. Will update accordingly.

**Pull request merged**
