### PR TITLE
Add 0x0603 for arbitrary bytes

### PR DESCRIPTION
**Pull request by staltz**
Full context is here: https://github.com/ssb-ngi-pointer/ssb-bfe/issues/19

This PR is still very much open for feedback

### CODE REVIEW

**Review by arj03 — APPROVED** [review]

**Review by cryptix — APPROVED** [review]
No objections (see https://github.com/ssb-ngi-pointer/ssb-bfe/issues/19#issuecomment-895933505)

**Comment by staltz** [comment]
Thanks. If anyone thinks of a better name for "arbitrary bytes", this spec can be updated in a non-breaking manner, what's important is to define 0x0603

**Comment by mixmix** [comment]
This is the "any" or anyBytes

I want to see the BFE.json moved to this spec so that it's canonical and forced to be in line with these sorts of PR.

Can you tell me why you need arbitrary bytes in  BFE format?
How about a proposal where we make type 127 a junk experimental type, then things can be upgraded once production ready?

**Comment by staltz** [comment]
@mixmix Would you have wanted to review this? I forgot to tag you as a reviewer.

You have a good point that 0603 could be (ab)used for passing "meaningful" buffers such as signatures or feed IDs.

**Pull request merged**
